#pragma once

const int ADMIN_MAIN_MENU_ADD_CHOICE = 1;
const int ADMIN_MAIN_MENU_REMOVE_CHOICE = 2;
const int ADMIN_MAIN_MENU_UPDATE_CHOICE = 3;
const int ADMIN_MAIN_MENU_LIST_ALL_CHOICE = 4;
const int ADMIN_MAIN_MENU_EXIT_CHOICE = 7;

const int USER_MAIN_MENU_PARSE_CHOICE = 1;
const int USER_MAIN_MENU_DELETE_CHOICE = 2;
const int USER_MAIN_MENU_SEE_LIST_INTERN_CHOICE = 3;
const int USER_MAIN_MENU_SEE_LIST_EXTERN_CHOICE = 4;
const int USER_MAIN_MENU_EXIT_CHOICE = 7;

const int USER_PARSE_MENU_OPEN_LINK_CHOICE = 1;
const int USER_PARSE_MENU_ADD_CHOICE = 2;
const int USER_PARSE_MENU_NEXT_CHOICE = 3;
const int USER_PARSE_MENU_EXIT_CHOICE = 7;

const int DATE_FIRST_SEPARATOR_INDEX = 4;
const int DATE_SECOND_SEPARATOR_INDEX = 7;

const int HOUR_SEPARATOR_INDEX = 2;
